# Generated by Django 4.1.3 on 2022-11-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passanger',
            new_name='Passenger',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='dlight_number',
            new_name='flight_number',
        ),
    ]
