# Generated by Django 4.1.3 on 2022-12-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_rename_passanger_passenger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='passanger',
            new_name='passenger',
        ),
    ]
